//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public short UserId { get; set; }
        public Nullable<byte> RoleId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
